/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort_PinMap.h"
#include "Port/Io/IfxPort_Io.h"
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include "string.h"
#include "UART_VCOM.h"

/* Scheduler includes */
#include "FreeRTOS.h"
#include "task.h"

#define LED_1                   IfxPort_P00_5               /* Port/Pin for LED 1 */
#define LED_2                   IfxPort_P00_6               /* Port/Pin for LED 2 */
#define BUTTON                  IfxPort_P00_7               /* Port/Pin for Button */

#define LED1_BLINKY_PERIOD_MS   (250)                       /* The period (in milliseconds) at which LED1 will blink */
#define BUTTON_PERIOD_MS        (25)                        /* The period (in milliseconds) */
#define STATUS_PERIOD_MS        (500)                        /* The period (in milliseconds) */


IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

uint8 step = 1;
char arr[64];
Ifx_SizeT count = 0;


/* Initialization function for LED1 app */
static void T_Led_init(void)
{
    /* Setup the port/pin connected to LED1 to general output mode push-pull. This function can be
     * used to initialize any port pin by specifying the port number, pin number and port pin mode.
     */
    IfxPort_setPinMode(LED_1.port, LED_1.pinIndex, IfxPort_Mode_outputPushPullGeneral);
}

static void T_Button_init(void)
{
    /* Setup the port/pin connected to Button to general input mode pull up. This function can be
     * used to initialize any port pin by specifying the port number, pin number and port pin mode.
     */
    IfxPort_setPinMode(BUTTON.port, BUTTON.pinIndex, IfxPort_Mode_inputPullUp);
}

static void T_Status_init(void)
{
    /* Setup the port/pin connected to LED1 to general output mode push-pull. This function can be
     * used to initialize any port pin by specifying the port number, pin number and port pin mode.
     */
}


/* Task which runs the LED1 app */
void T_Led(void *arg)
{
    TickType_t lastTick = xTaskGetTickCount();

    T_Led_init();
    while (1)
    {
        /* Toggle LED1 state */
        IfxPort_setPinState(LED_1.port, LED_1.pinIndex, IfxPort_State_toggled);

        /* Delay 250ms */
        xTaskDelayUntil(&lastTick,100*step);
    }
}

/* Task which handles button */
void T_Button(void *arg)
{
    T_Button_init();

    while (1)
    {
        /* Toggle LED1 state */
        if(!IfxPort_getPinState(BUTTON.port, BUTTON.pinIndex))
        {
            step++;
            if (step > 3)
            {
                step = 1;
            }
        }

        /* Delay 25ms */
        vTaskDelay(pdMS_TO_TICKS(BUTTON_PERIOD_MS));
    }
}

/* Task which handles tasks status */
void T_Status(void *arg)
{
    TaskHandle_t xHandle_Led;
    TaskHandle_t xHandle_Button;
    TaskStatus_t xTaskDetails_Led;
    TaskStatus_t xTaskDetails_Button;

    T_Status_init();

    // Obtain the handle of a task from its name.
    xHandle_Led = xTaskGetHandle( "LED" );
    xHandle_Button = xTaskGetHandle( "BUTTON" );

    // Check the handle is not NULL.
    configASSERT( xHandle_Led );
    configASSERT( xHandle_Button );

    while (1)
    {
        // Use the handle to obtain further information about the task.
        vTaskGetInfo( xHandle_Led,
                &xTaskDetails_Led,
                pdTRUE, // Include the high water mark in xTaskDetails.
                eInvalid ); // Include the task state in xTaskDetails.

        // Use the handle to obtain further information about the task.
        vTaskGetInfo( xHandle_Button,
                &xTaskDetails_Button,
                pdTRUE, // Include the high water mark in xTaskDetails.
                eInvalid ); // Include the task state in xTaskDetails.

        send_UART_message((char *)xTaskDetails_Led.pcTaskName,configMAX_TASK_NAME_LEN);
        strcpy(arr,": ");
        count = 2;
        send_UART_message(arr,count);

        switch (xTaskDetails_Led.eCurrentState)
        {
            case eRunning:
                strcpy(arr,"Running");
                count = 7;
                break;

            case eReady:
                strcpy(arr,"Ready");
                count = 5;
                break;

            case eBlocked:
                strcpy(arr,"Blocked");
                count = 7;
                break;

            case eSuspended:
                strcpy(arr,"Suspended");
                count = 9;
                break;

            case eDeleted:
                strcpy(arr,"Deleted");
                count = 7;
                break;

            default:
                strcpy(arr,"Invalid");
                count = 7;
                break;
        }
        send_UART_message(arr,count);

        strcpy(arr,"\n");
        count = 1;
        send_UART_message(arr,count);

        send_UART_message((char *)xTaskDetails_Button.pcTaskName,configMAX_TASK_NAME_LEN);
        strcpy(arr,": ");
        count = 2;
        send_UART_message(arr,count);

        switch (xTaskDetails_Button.eCurrentState)
        {
            case eRunning:
                strcpy(arr,"Running");
                count = 7;
                break;

            case eReady:
                strcpy(arr,"Ready");
                count = 5;
                break;

            case eBlocked:
                strcpy(arr,"Blocked");
                count = 7;
                break;

            case eSuspended:
                strcpy(arr,"Suspended");
                count = 9;
                break;

            case eDeleted:
                strcpy(arr,"Deleted");
                count = 7;
                break;

            default:
                strcpy(arr,"Invalid");
                count = 7;
                break;
        }
        send_UART_message(arr,count);

        strcpy(arr,"\n");
        count = 1;
        send_UART_message(arr,count);

        /* Delay 1000ms */
        vTaskDelay(pdMS_TO_TICKS(STATUS_PERIOD_MS));
    }
}

void core0_main(void)
{
    BaseType_t res;

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    /* Initialize UART */
    init_UART();

    /* Create the Blinky task */
    res = xTaskCreate(T_Led, "LED", configMINIMAL_STACK_SIZE, NULL, 2, NULL);
    res |= xTaskCreate(T_Button, "BUTTON", configMINIMAL_STACK_SIZE, NULL, 3, NULL);
    res |= xTaskCreate(T_Status, "STATUS", configMINIMAL_STACK_SIZE, NULL, 4, NULL);

    if (res != pdPASS)
    {
        configASSERT(res);
    }
    /* Start the scheduler (this function will never return) */
    vTaskStartScheduler();
    while(1)
    {
    }
}

/* Required FreeRTOS callback, called in case of a stack overflow.
 * For the sake of simplicity, this function will loop indefinitely
 * and the root cause can be confirmed by using a debugger
 */
void vApplicationStackOverflowHook (TaskHandle_t xTask, char *pcTaskName)
{

}
