/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort_PinMap.h"
#include "Port/Io/IfxPort_Io.h"
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include "String.h"
#include "UART_VCOM.h"

/* Scheduler includes */
#include "FreeRTOS.h"
#include "task.h"

#define LED_1                   IfxPort_P00_5               /* Port/Pin for LED 1 */
#define LED_2                   IfxPort_P00_6               /* Port/Pin for LED 2 */
#define BUTTON                  IfxPort_P00_7               /* Port/Pin for Button */

#define LED1_BLINKY_PERIOD_MS   (250)                       /* The period (in milliseconds) at which LED1 will blink */
#define BUTTON_PERIOD_MS        (25)                        /* The period (in milliseconds) */
#define STATUS_PERIOD_MS        (500)                        /* The period (in milliseconds) */


IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

char arr[64] = "\n";
Ifx_SizeT count = 0;

uint8 x,y;

static void T_Count_init(void)
{

}

static void T_Check_init(void)
{
    init_UART();
}



void T_Count(void *arg)
{
    T_Count_init();

    while(1)
    {
        vTaskSuspendAll(); /* used in case of ISR need to be running */
//        vPortEnterCritical(); /* used in case of ISR need to be stopped */
        x++;

        y++;
        xTaskResumeAll();
//        vPortExitCritical();
    }
}

void T_Check(void *arg)
{
    T_Check_init();

    while(1)
    {
        if(x!=y)
        {
            strcpy(arr,"x and y don't match\n");
            send_UART_message(arr,20);
        }
        vTaskDelay(40);
    }

}

void core0_main(void)
{
    BaseType_t res;

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    res = xTaskCreate(T_Count, "COUNT", configMINIMAL_STACK_SIZE, NULL, 2, NULL);
    res |= xTaskCreate(T_Check, "CHECK", configMINIMAL_STACK_SIZE, NULL, 3, NULL);

    if (res != pdPASS)
    {
        configASSERT(res);
    }
    /* Start the scheduler (this function will never return) */
    vTaskStartScheduler();
    while(1)
    {
    }
}

/* Required FreeRTOS callback, called in case of a stack overflow.
 * For the sake of simplicity, this function will loop indefinitely
 * and the root cause can be confirmed by using a debugger
 */
void vApplicationStackOverflowHook (TaskHandle_t xTask, char *pcTaskName)
{

}
